config/routes.rb
Rails.application.routes.draw do

  resources :foods
  resources :categories
  resources :orders
  resources :customers
  resources :restaurants
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: "users/registrations"
  }

  root "restaurants#index"

end

app/views/shared/_aside.html.erb
<aside class="js-navbar-vertical-aside navbar navbar-vertical-aside navbar-vertical navbar-vertical-fixed navbar-expand-xl navbar-bordered navbar-dark navbar-vertical-aside-initialized">
  <div class="navbar-vertical-container">
    <div class="navbar-vertical-footer-offset pb-0">
      <div class="navbar-brand-wrapper justify-content-between">
        <!-- Logo -->

        <a class="navbar-brand" href="<%= root_path %>" aria-label="Front">
          <%#= image_tag "logo.png", class: "navbar-brand-logo", alt: "Logo", style: "height: 40px; width: 40px; min-width: unset" %>
          <%#= image_tag "logo.png", class: "navbar-brand-logo-mini", alt: "Logo", style: "height: 40px; width: 40px; min-width: unset" %>
        </a>

        <!-- End Logo -->

        <!-- Navbar Vertical Toggle -->
        <button type="button" class="js-navbar-vertical-aside-toggle-invoker navbar-vertical-aside-toggle btn btn-icon btn-xs btn-ghost-dark">
          <i class="tio-clear tio-lg"></i>
        </button>
        <!-- End Navbar Vertical Toggle -->
      </div>

      <!-- Content -->
      <div class="navbar-vertical-content">
        <ul class="navbar-nav navbar-nav-lg nav-tabs">

          <li class="nav-item">
            <small class="nav-subtitle" title="Pages">Admin</small>
            <small class="tio-more-horizontal nav-subtitle-replacer"></small>
          </li>

          <li class="nav-item ">
            <a class="js-nav-tooltip-link nav-link " href="<%= restaurants_path %>" title="" data-placement="left" data-original-title="Layouts">
              <%#= fa_icon('coffee', class: "nav-icon") %>
              <span class="navbar-vertical-aside-mini-mode-hidden-elements text-truncate">Restaurants</span>
            </a>
            <a class="js-nav-tooltip-link nav-link " href="<%= customers_path %>" title="" data-placement="left" data-original-title="Layouts">
              <%#= fa_icon('coffee', class: "nav-icon") %>
              <span class="navbar-vertical-aside-mini-mode-hidden-elements text-truncate">Customers</span>
            </a>
            <a class="js-nav-tooltip-link nav-link " href="<%= orders_path %>" title="" data-placement="left" data-original-title="Layouts">
              <%#= fa_icon('coffee', class: "nav-icon") %>
              <span class="navbar-vertical-aside-mini-mode-hidden-elements text-truncate">Orders</span>
            </a>
            <a class="js-nav-tooltip-link nav-link " href="<%= categories_path %>" title="" data-placement="left" data-original-title="Layouts">
              <%#= fa_icon('coffee', class: "nav-icon") %>
              <span class="navbar-vertical-aside-mini-mode-hidden-elements text-truncate">Categories</span>
            </a>
            <a class="js-nav-tooltip-link nav-link " href="<%= foods_path %>" title="" data-placement="left" data-original-title="Layouts">
              <%#= fa_icon('coffee', class: "nav-icon") %>
              <span class="navbar-vertical-aside-mini-mode-hidden-elements text-truncate">Foods</span>
            </a>
          </li>
        </ul>
      </div>
      <!-- End Content -->
    </div>
  </div>
</aside>

app/views/shared/_header.html.erb
<header id="header" class="navbar navbar-expand-lg navbar-fixed navbar-height navbar-flush navbar-container navbar-bordered">

</header>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
      <% flash.each do |key, value| %>
      <% type = key.to_s.gsub('alert','error').gsub('notice','success') %>
      toastr['<%= type %>']('<%= value %>');
      <% end %>
  </script>
<% end %>

app/views/shared/_message_html.html.erb
<% flash.each do |name, msg| %>
  <% if msg.class == Array %>
    <% msg.each do |message| %>
      <%= content_tag :div, message, :id => "flash_#{name}" %>
    <% end %>
  <% else %>
    <%= content_tag :div, msg, :id => "flash_#{name}", class: "my-3 text-danger" %>
  <% end %>
<% end %>